### ISSUE TITLE
commhub

### ISSUE THREAD

**Issue by vkuehn** [jeffbass/yin-yang-ranch#6]
Hi,

is that still active ?
If so where to do you work on the commhub stuff ?

From your screenshot it looks like it is already working ?!?

**Comment by jeffbass** [comment]
I have had the prototype librarian and commhub working for about 3 years. The SMS texting comm agent uses a Google Voice telephone number (and the Gmail API) for receiving and sending the SMS texts shown in the example. There is also a simple terminal CLI query comm agent. They are simple prototypes, but may be helpful as an example. I'll upload the Python code later this week.

**Comment by jeffbass** [comment]
Hi @vkuehn,

I pushed the `librarian-prototype` to this repository. It contains the code for the `commhub` and the code I use to send / receive SMS texts using a Google Voice phone number via the Gmail API. The code is in the ``librarian-protype`` folder. The documentation is [here](https://github.com/jeffbass/yin-yang-ranch/blob/master/docs/librarian-prototype.rst).

**Comment by vkuehn** [comment]
excellent, Thanks for that
